### ISSUE TITLE
Root not writeable on MacOS

### ISSUE THREAD

**Issue by acdoussan** [Ableton/ansible-role-nix#119]
I get the following error when trying to run this role on MacOS

```
TASK [ableton.nix : Ensure Nix directory exists] *********************************************************************************************************
fatal: [127.0.0.1]: FAILED! => changed=false 
  msg: 'There was an issue creating /nix as requested: [Errno 30] Read-only file system: b''/nix'''
  path: /nix
```

It turns out the root volume is read-only on MacOS. I am not sure what a good solve is for this right now.

**Comment by acdoussan** [comment]
https://stackoverflow.com/questions/73048614/can-i-mount-the-root-system-filesystem-as-writable-in-macos-monterey

Seems like going down the path of making the root volume writable is not a good idea, probably best to use a different location if possible?

**Comment by acdoussan** [comment]
https://nixos.org/download.html#nix-install-macos

https://nixos.org/manual/nix/stable/installation/installing-binary.html#macos-installation

Looks like the recommendation is to use a separate volume and update `/etc/synthetic.conf`

Is there any major benefit to using this ansible role over using the install scripts provided by nixos?

**Comment by nre-ableton** [comment]
@acdoussan I have pushed a potential fix for this issue: https://github.com/Ableton/ansible-role-nix/pull/121

If you could try out this branch and let me know if it works, that would be very useful, as I don't have a Mac to test on. Otherwise it "should work" (famous last words :sweat_smile:).
